spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness
      database: airecommendationfitness
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Use JsonDeserializer for values (so bytes -> com.fitness.aiservice.model.Activity)
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        # fully qualified class the deserializer should map the JSON to
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

# separate, non-spring kafka app settings
kafka:
  topic:
    name: activity-events

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}